### ISSUE TITLE
plainvit_large448_sbd.py and plainvit_large448_cocolvis.py

### ISSUE THREAD

**Issue by Vlad188-1** [TitorX/CFR-ICL-Interactive-Segmentation#4]
Hello! Can I ask you to add files for training a large model?
**(plainvit_large448_sbd.py** and **plainvit_large448_cocolvis.py)**

**Comment by Divya9Sasidharan** [comment]
Training for large can be replicated from [simpleclick](https://github.com/uncbiag/SimpleClick/blob/v1.0/models/iter_mask/plainvit_large448_cocolvis_itermask.py) . For example plainvit_large448_cocolvis.py  backbone, neck and head param is as follows . 

` backbone_params = dict(
        img_size=model_cfg.crop_size,
        patch_size=(16,16),
        in_chans=3,
        embed_dim=1024,
        depth=24,
        num_heads=16,
        mlp_ratio=4, 
        qkv_bias=True,
    )`

    neck_params = dict(
        in_dim = 1024,
        out_dims = [192, 384, 768, 1536],
    )

    
    head_params = dict(
        in_channels=[192, 384, 768, 1536],
        in_index=[0, 1, 2, 3],
        dropout_ratio=0.1,
        num_classes=1,
        loss_decode=CrossEntropyLoss(),
        align_corners=False,
        upsample=cfg.upsample,
        channels={'x1': 256, 'x2': 128, 'x4': 64}[cfg.upsample],
    )`

**Comment by Vlad188-1** [comment]
@Divya9Sasidharan Thank you very much for your answer!
